### ISSUE TITLE
KeyError: 'exchangeTimezoneName' when accessing ticker history

### ISSUE THREAD

**Issue by manoelmarques** [ranaroussi/yfinance#1076]
Current yfinance 0.1.75 raises an exception when running  the following:
```
import yfinance as yf


def _main():
    stock_data = yf.download(
        "AFN",
        start="2018-01-01",
        end="2018-12-31",
        group_by="ticker",
        threads=False
    )
    print(stock_data)


if __name__ == "__main__":
    _main()
```
```
  stock_data = yf.download(
  File "/Users/manoel/opt/anaconda3/envs/Qiskitenv/lib/python3.8/site-packages/yfinance/multi.py", line 120, in download
    data = _download_one(ticker, period=period, interval=interval,
  File "/Users/manoel/opt/anaconda3/envs/Qiskitenv/lib/python3.8/site-packages/yfinance/multi.py", line 205, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/Users/manoel/opt/anaconda3/envs/Qiskitenv/lib/python3.8/site-packages/yfinance/base.py", line 148, in history
    end = utils._parse_user_dt(end, self._get_ticker_tz())
  File "/Users/manoel/opt/anaconda3/envs/Qiskitenv/lib/python3.8/site-packages/yfinance/base.py", line 328, in _get_ticker_tz
    tkr_tz = self.info["exchangeTimezoneName"]
KeyError: 'exchangeTimezoneName'
```

Running the same sample against the previous release returns:
```
[*********************100%***********************]  1 of 1 completed
                 Open       High        Low      Close  Adj Close  Volume
Date                                                                     
2018-01-02  29.799999  29.799999  29.799999  29.799999  29.799999       0
2018-01-03  30.000000  30.000000  30.000000  30.000000  30.000000       0
2018-01-04  30.000000  30.000000  30.000000  30.000000  30.000000       0
2018-01-05  30.200001  30.200001  30.200001  30.200001  30.200001       0
2018-01-08  30.000000  30.000000  30.000000  30.000000  30.000000       0
2018-01-09  30.200001  30.200001  30.200001  30.200001  30.200001       0
2018-01-10  32.799999  32.799999  32.799999  32.799999  32.799999       0
2018-01-11  31.799999  31.799999  31.799999  31.799999  31.799999       0
2018-01-12  30.799999  30.799999  30.799999  30.799999  30.799999       0
2018-01-16  30.200001  30.200001  30.200001  30.200001  30.200001       0
2018-01-17  30.799999  30.799999  30.799999  30.799999  30.799999       0
2018-01-18  30.799999  30.799999  30.799999  30.799999  30.799999       0
2018-01-19  30.799999  30.799999  30.799999  30.799999  30.799999       0
2018-01-22  31.400000  31.400000  31.400000  31.400000  31.400000       0
2018-01-23  32.000000  32.000000  32.000000  32.000000  32.000000       0
2018-01-24  31.600000  31.600000  31.600000  31.600000  31.600000       0
2018-01-25  31.200001  31.200001  31.200001  31.200001  31.200001       0
2018-01-26  32.200001  32.200001  32.200001  32.200001  32.200001       0
2018-01-29  31.799999  31.799999  31.799999  31.799999  31.799999       0
2018-01-30  31.520000  31.520000  31.520000  31.520000  31.520000       0
```

If I run with `threads=True` it will raise the exception and hang.

**Comment by ValueRaider** [comment]
What is "AFN"? I don't see it in Yahoo. And the old price data looks bad - 0 volume, low=high.

**Comment by manoelmarques** [comment]
The example above is actually from the London Stock Exchange. I found that using "AFN.L" it returns data and doesn't raise an exception .

So it seems the exception in the new release happens for invalid tickers. If I enter ticker "???" in the new release I get the key error exception. In the previous  version there was no key error, just a printed message:
```
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ???: No data found for this date range, symbol may be delisted
```

**Comment by ValueRaider** [comment]
That's a good point, it should print a nice message. Will fix it.

**Comment by felixlulz** [comment]
hey, i got the same error. it used to print 

BEFORE:

KGF.L
0
[*********************100%***********************]  1 of 1 completed
LAND.L
1
[*********************100%***********************]  1 of 1 completed
LGEN.L
2
[*********************100%***********************]  1 of 1 completed
LLOY.L
3
[*********************100%***********************]  1 of 1 completed
LSEG.L
4
[*********************100%***********************]  1 of 1 completed
MNG.L
5
[*********************100%***********************]  1 of 1 completed
MGGT.L
6
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ???: No data found for this date range, symbol may be delisted
-----

NOW:

raises error and hangs like this when i loop trough the ticker symbols. not fixable with try/except

KGF.L
0
[*********************100%***********************]  1 of 1 completed
LAND.L
1
[*********************100%***********************]  1 of 1 completed
LGEN.L
2
[*********************100%***********************]  1 of 1 completed
LLOY.L
3
[*********************100%***********************]  1 of 1 completed
LSEG.L
4
[*********************100%***********************]  1 of 1 completed
MNG.L
5
[*********************100%***********************]  1 of 1 completed
MGGT.L
6
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yfinance/multi.py", line 193, in _download_one_threaded
    keepna, timeout)
  File "/usr/local/lib/python3.7/dist-packages/yfinance/multi.py", line 210, in _download_one
    timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/yfinance/base.py", line 148, in history
    end = utils._parse_user_dt(end, self._get_ticker_tz())
  File "/usr/local/lib/python3.7/dist-packages/yfinance/base.py", line 328, in _get_ticker_tz
    tkr_tz = self.info["exchangeTimezoneName"]
KeyError: 'exchangeTimezoneName'

hoping for a fix soon, thanks for your work and help

**Comment by Lifeof31415926535** [comment]
My interpreter returned this error message.
.../yfinance/base.py", line 341, in _get_ticker_tz
    tkr_tz = self.info["exchangeTimezoneName"]
KeyError: 'exchangeTimezoneName'.

The issues seems to be related to line 341.  I think self.info needs to be changed to self._info.

https://github.com/ranaroussi/yfinance/blob/51f2c7301dfadcc64ad9d22f36a846f999860358/yfinance/base.py#L340-L346

**Comment by ValueRaider** [comment]
Should be fixed now

**Comment by c0mm0d0re** [comment]
This problem still exists with the new the latest .77 version. Before releasing a patch/update you need to run your main test script (the one that contains all the functions of the lib with all of the stock symbols to make sure it is safe to release). 
To reproduce this:
1. Get all usa stocks into a list named 'all_assets' from a reliable source like finra or nasdaq (https://www.nasdaq.com/market-activity/stocks/screener). 
2. Execute: data = yf.download(all_assets,start=(datetime.datetime.now()-datetime.timedelta(days=1)).strftime("%Y-%m-%d"),timeout=5)

There is no issue with the .74 version.

**Comment by ValueRaider** [comment]
@c0mm0d0re Can you provide code that reproduces bug? I am getting correct behaviour for both listed and delisted tickers.

**Comment by c0mm0d0re** [comment]
@ValueRaider I haven't gone through your code but if you do the steps below and you should see an error - i think something related to this error that you altered or another but def connected to this. 

1. tickers = [] # get the tickers from here: https://pastebin.com/rhapPCyr
2. data = yf.download(tickers, start=(datetime.datetime.now()-datetime.timedelta(days=1)).strftime("%Y-%m-%d"),timeout=5)

**Comment by ValueRaider** [comment]
I'm not going to run every ticker in the universe and get my IP blocked/restricted. Just tell me what ticker failed for you.

**Comment by fredrik-corneliusson** [comment]
I'm having the same issue (using the dev branch)
Looking at the code there is a safeguard that checks for the key `exchangeTimezoneName` in `self.info` before getting it.
```
if not 'exchangeTimezoneName' in self.info:
    return None
tz = self.info["exchangeTimezoneName"]
```

However as info is backed by a property function (defined in the subclass) and calls self.get_info (defined in base class) it probably does multiple requests and the self.info can differ.

```
    @property
    def info(self):
        return self.get_info() 
```

I updated the code in my forked dev branch so this issue should not be possible.
[fork](https://github.com/fredrik-corneliusson/yfinance-tz-cache/tree/dev)

**However, the fact that the old code got different results from consecutive calls to self.get_info() is the root cause of this bug and not something my code change fixes**

My Traceback:
```
Exception in thread Thread-1000:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File .virtualenvs/screener/lib/python3.7/site-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/yfinance-tz-cache/yfinance/multi.py", line 201, in _download_one_threaded
    keepna, timeout)
  File "/yfinance-tz-cache/yfinance/multi.py", line 218, in _download_one
    timeout=timeout)
  File "/yfinance-tz-cache/yfinance/base.py", line 157, in history
    tz = self._get_ticker_tz()
  File "/yfinance-tz-cache/yfinance/base.py", line 400, in _get_ticker_tz
    tz = self.info["exchangeTimezoneName"]
KeyError: 'exchangeTimezoneName'
```

**Comment by ValueRaider** [comment]
> it probably does multiple requests and the self.info can differ.

It does make multiple requests but only the first will do work. All subsequent requests will quickly return: https://github.com/ranaroussi/yfinance/blob/34dfe944d9c48640d5b8e5e1a30968d21acc1a17/yfinance/base.py#L362

Were you able to reliably produce 'different results from consecutive calls'?

**Comment by fredrik-corneliusson** [comment]
That depends:
https://github.com/ranaroussi/yfinance/blob/34dfe944d9c48640d5b8e5e1a30968d21acc1a17/yfinance/base.py#L358
The get info does a lot of requests and some of them fails in the first call that set `self._info`, `self._sustainability` or  `self._recommendations` then all requests are redone if I read the code correctly.

**Comment by fredrik-corneliusson** [comment]
Have now tired to understand the code a bit more.
The `get_info` method only does one HTTP request but a lot of parsing of that request.
If the parsing of request response fails on _sustainability or _recommendations fails it will redo the HTTP request next time it is called.

**Comment by ValueRaider** [comment]
I understand now. Changing that if-statement from `or`s to `and`s seems best.

**Comment by fredrik-corneliusson** [comment]
I created a #1109 with my fix, it does however not use `and` in the if statment just a simplified version of the if statment. I can update that if you feel that change would be safe.

**Comment by fredrik-corneliusson** [comment]
@ValueRaider I looked at the json result we get from the endpoint that gets history ticker data
e.g https://query2.finance.yahoo.com/v8/finance/chart/TSLA
In that response there is already "exchangeTimezoneName" present.
Why do we get the timezone information from the scraping endpoint instead of from the ticker history response directly?
Using the scraping endpoint is probably slower and more error prone.

**Comment by ValueRaider** [comment]
At that point in the code, where start & end dates being processed, the price request hasn't been sent.

**Comment by fredrik-corneliusson** [comment]
Yes, but would it not be better to use that endpoint (giving a minimal period) to get the timezone?
That way any HTML scraping (and dependency on html not changing) would be avoided.
I did a quick comparison between the 2 endpoints and the 

- https://finance.yahoo.com/quote ~700ms
- https://query2.finance.yahoo.com/v8/finance/chart/TSLA?period1=1666609904&period2=1666609904&interval=1d ~70ms

So it would be a speedup of 10 times.

And the extra query to ticker data could be avoided completely for longer ticker timeintervals (>1d) by asking for an extra day before and after and do the timezone filtering in of the returned data.

**Comment by ValueRaider** [comment]
Good point. I'll push an update to `dev`

**Comment by fredrik-corneliusson** [comment]
If you are going to do multiple request to query2 to get the timezone maybe the code that does the request should be refactored in order to be reused.

I noted that this try/except clause effectively negates the explicit raising of runtime error to inform about yahoo is down.
https://github.com/ranaroussi/yfinance/blob/dev/yfinance/base.py#L211-L226

What is the desired behaviour? Code like this seems very ambiguous error prone to me.
In most cases silencing all exceptions is a bad idea, instead catch the ones you are expecting and handle them (logging or re-raising etc.) and in case of unexpected exception at least log it if you catch it.

**Comment by ValueRaider** [comment]
So that `catch` predates me. Introduced by PR #907, maybe they forgot to remove it - Ran has a habit of merging without reviewing.

Regarding timezone - I've pushed to `fix/get-tz-performance`. Actual performance boost not as good as 10x because still requires json parsing. Maybe I'm missing an obvious optimisation?

**Comment by ValueRaider** [comment]
Can everyone update to 0.1.84 then report on the status of the bug? Is it solved?

**Comment by fredrik-corneliusson** [comment]
Seems solved for me.
