### ISSUE TITLE
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

### ISSUE THREAD

**Issue by DolevAlgam** [ranaroussi/yfinance#1329]
I use Python 3.8
Installed yfinance 0.2.4
I'm pulling the info of a ticker using this code:
`info = yf.Ticker(symbol).info`
And I'm getting this error message:

> Exception("Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption: '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> ,
And it continues with a ton of <class 'str'> like above.

Does someone know how to fix it?

**EDIT from @ValueRaider**
In case you're confused by title not matching this top post - I edited title to reflect the latest error message. Discussion below still very relevent.

**Comment by ValueRaider** [comment]
I've quickly tested and working for me. But there is a bug in generating that error message rendering it useless - can you try again with Git branch `hotfix/decryption`.

**Comment by DavidLambertCyber** [comment]
I ran into same issue today, system reboot fixed for me.

**Comment by BugByteMan** [comment]
I updated my code to handle the exception and retry the request.  That has fixed the issue for me.

**Comment by mm0** [comment]
> I've quickly tested and working for me.
> 
> Error message tells us there are 8 fields when `yfinance` expected 1. But there is a bug in generating that error message, that's why all print same - can you try again with Git branch `hotfix/decryption`.

Hi, I have tried this branch and it doesn't seem to fix the issue

**Comment by mm0** [comment]
> I never said it would fix the decryption.

Okay.  In case it helps, the issue seems to occur with paginated requests.

**Comment by ValueRaider** [comment]
What will help is posting the fixed error message.

**Comment by swilson2020** [comment]
This is what I'm getting.

File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/steven/Python/Scanner/data_manager/workers.py", line 459, in run
    self._pull_funds(ticker.symbol)
  File "/home/steven/Python/Scanner/data_manager/workers.py", line 410, in _pull_funds
    yf_funds = self._yf_model.get_fundamentals(yf_ticker)
  File "/home/steven/Python/Scanner/models/apimodels.py", line 516, in get_fundamentals
    data = yf_ticker.info
  File "/home/steven/.local/share/virtualenvs/Scanner-W2wrJ_Cc/lib/python3.10/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/home/steven/.local/share/virtualenvs/Scanner-W2wrJ_Cc/lib/python3.10/site-packages/yfinance/base.py", line 895, in get_info
    data = self._quote.info
  File "/home/steven/.local/share/virtualenvs/Scanner-W2wrJ_Cc/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 27, in info
    self._scrape(self.proxy)
  File "/home/steven/.local/share/virtualenvs/Scanner-W2wrJ_Cc/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 56, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "/home/steven/.local/share/virtualenvs/Scanner-W2wrJ_Cc/lib/python3.10/site-packages/yfinance/data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "/home/steven/.local/share/virtualenvs/Scanner-W2wrJ_Cc/lib/python3.10/site-packages/yfinance/data.py", line 202, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data)
  File "/home/steven/.local/share/virtualenvs/Scanner-W2wrJ_Cc/lib/python3.10/site-packages/yfinance/data.py", line 73, in decrypt_cryptojs_aes_stores
    raise Exception(msg)
Exception: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption: '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> ,

**Comment by mm0** [comment]
> 

The error message with your branch is attached
[msg.txt](https://github.com/ranaroussi/yfinance/files/10485856/msg.txt)

**Comment by dschaefer** [comment]
Seems to be the same error message on the branch. It is intermittent. I'm fetching about 24 tickers one at a time in my script and hits pretty randomly.

**Comment by dschaefer** [comment]
Seems like the first key works anyway. I simply removed the check for l == 1. Not sure that's the right answer though.

**Comment by EmirEgilli** [comment]
Getting the exact same error. Will have to wait for a fix i guess.

**Comment by ValueRaider** [comment]
Thanks @mmm0. Wow that is a lot of keys. I've made two more changes to branch, please run again:
1. discard `new_keys` that point to same value - potential fix
2. improve error message to print the values too

**Comment by james-stevens** [comment]
> Okay. In case it helps, the issue seems to occur with paginated/large? requests.

I'm getting this issue when I run a number of requests, but it seems OK if I just do a single request, by hand

I wonder if they've added some kind of frequency of request checks?

**Comment by Korach250** [comment]
**Exception: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption**

Getting the above issue for ticker :   AGFY                                             

Exception                                 Traceback (most recent call last)
[<ipython-input-23-2801be2dafb2>](https://localhost:8080/#) in <module>
     40 
     41     flt_shares = {}
---> 42     flt_shares[f'{symbol}'] = ticker.info.get('floatShares')
     43     df['Float'] = (flt_shares[f'{symbol}'])
     44 

6 frames
[/usr/local/lib/python3.8/dist-packages/yfinance/data.py](https://localhost:8080/#) in decrypt_cryptojs_aes_stores(data)
     71             for i in range(1, len(new_keys)):
     72                 msg += f" , '{k_str}'->{type(data[k])}"
---> 73             raise Exception(msg)
     74         password_key = new_keys[0]
     75         password = data[password_key]

Exception: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption: '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb7...

**Comment by ValueRaider** [comment]
@Korach250 Read the entire thread before posting.

**Comment by AlefTester** [comment]
Hello!
I'm really new to all of this...
But I had my python code working with yFinance...
And now I also get this Exception "Yahoo has changed the format again..."
I mean I had a problem with 0.2.3 version... updated yesterday and it was fine.
Now this.

Should I wait for the fix and do nothing ?
Or we don't know yet what to do? :(

**Comment by ValueRaider** [comment]
@AlefTester Start by reading this thread.

**Comment by mm0** [comment]
> Thanks @mmm0. Wow that is a lot of keys. I've made two more changes to branch, please run again:
> 
> 1. discard `new_keys` that point to same value - potential fix
> 2. improve error message to print the values too
> 
> In case not obvious: feedback wanted

[msg.txt](https://github.com/ranaroussi/yfinance/files/10494144/msg.txt)

**Comment by ValueRaider** [comment]
@mm0 That new file has 2x more keys than the previous. And I'm not seeing the usual traffic spike that accompanies a Yahoo change (GitHub, Twitter, etc). I don't understand ...

Anyway I've pushed another change to hardcode the key (thanks @ifel), try that.

**Comment by Lagersuufer** [comment]
Not sure if this is significant or not, but I was able to get my routines working again by using Ticker() and pulling info individually instead of the Tickers() list call.

**Comment by hepizoj22** [comment]
> Not sure if this is significant or not, but I was able to get my routines working again by using Ticker() and pulling info individually instead of the Tickers() list call.
[msg.txt](https://github.com/ranaroussi/yfinance/files/10496031/msg.txt)

Doesn't work for me. I'm using Ticker() since the beginning.
it was working intermittently yesterday(had to restart kernel on jupyter) but now its always this exception.

**Comment by dschaefer** [comment]
With the latest `hotfix/decryption`, I'm now constantly getting:

```
  File "/opt/homebrew/lib/python3.10/site-packages/cryptography/hazmat/primitives/padding.py", line 101, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.
```

**Comment by dschaefer** [comment]
Using the first key isn't working anymore either. And I'm getting 10004 keys to pick from. They really are trying to make this hard. (And are probably watching this conversation).

**Comment by Rsoni205173** [comment]
> I use Python 3.8 Installed yfinance 0.2.4 I'm pulling the info of a ticker using this code: `info = yf.Ticker(symbol).info` And I'm getting this error message:
> 
> > Exception("Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption: '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> ,
> > And it continues with a ton of <class 'str'> like above.
> 
> Does someone know how to fix it?


>I am to facing same issue....

**Comment by tomekkurzydlak** [comment]
Same for me.
Python 3.10
yfinance 0.2.4
and since yesterday I got error trying:
coin = yf.Ticker(ticker)
price = coin.info['regularMarketPrice']

Exception("Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption: '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '80226cfb77c7'-><class 'str'> , '

**Comment by iometrine** [comment]
> I updated my code to handle the exception and retry the request. That has fixed the issue for me.

How did you do that ?

**Comment by Abhijitjimmi** [comment]
Facing same issue. Any update on how to solve it?

**Comment by james-stevens** [comment]
> Not sure if this is significant or not, but I was able to get my routines working again by using Ticker() and pulling info individually instead of the Tickers() list call.

I was using this code to get tickers one at a time (including reading all tickers returned each time), with random delays between each get and retrying ones that failed - that was OK for most of yesterday, but is now broken - the JSON returned by `get_json_data_stores()` is now just empty.
```
from yfinance import data as yfdata

ask = sys.argv[1].upper()
ticker = yfdata.TickerData(ask)
js = ticker.get_json_data_stores()
store = js["StreamDataStore"]["quoteData"]
```

**Comment by Sebastvin** [comment]
Any chance this bug will be fixed today? I'm using yfinance for a project I'm handing in for graduation tomorrow. Previously, the error occurred sometimes and restarting the code solved the problem, but today the error appears every time when I want to run the code

**Comment by iometrine** [comment]
waiting for him to fix, you can try to get the information differently  

        ticker = yf.Ticker('AAPL')
        hist  = ticker.history(period="1d")
        df = hist.reset_index()
        
        for index, row in df.iterrows():
            index = row['Close']

**Comment by dataTrying** [comment]
> 

Same here, I just pray that it will be solved quickly.

**Comment by ValueRaider** [comment]
For those that *need* the data, look into `yahooquery` Python module. Accesses non-price data different way so not affected by encryption, but their documentation sucks.

**Comment by EmirEgilli** [comment]
Situation definitely got worse compared to yesterday, some functions started to give out the same error even when used for one ticker. 

Issue was duplicated while trying to get calendar info to check for earnings season release dates. While normally this would suffice:

`import yfinance as yf`
`stock yf.Ticker("NFLX")`
`stock.calendar`

I am instead now using: `stock.get_earnings_dates()`

Here's hoping this would get resolved this week with a new update.

**Comment by SamZhang02** [comment]
I tried out a few other functionalities locally, there are some alternatives for people who need to access some data:
`Ticker.history()` is still usable for historical price data
`Ticker.get_history_metadata()` for non-price data such as exchange, timezone, currency, current price, etc.

I would agree with @ValueRaider's proposal on #1300, as it might provide a more stable user-experience for most users of yfinance, while also be less likely to make Yahoo mad by sending expensive requests like `.info`

**Comment by ValueRaider** [comment]
@SamZhang02 I'm fast-tracking #1300 now, see #1317 (merged into `dev` today).

**Comment by SamZhang02** [comment]
> @SamZhang02 I'm fast-tracking #1300 now, see #1317 (merged into `dev` today).

Good call, this might be a more definitive fix than to play back and forth with Yahoo. Thank you for the info.

**Comment by RudyNL** [comment]
I am still running my programs on a daily basis on version 0.1.96 and I am trying to convert towards 0.2.4. I am hardly influenced by these problems. Yahoo is offering two kinds of data, slowly modifying data en rapidly modifying data. These problems are mainly restricted to the slowly modifying data. Because I am using cashing and I still own an pretty accurate cash for the slowly modifying data, my programs are still running without problems. Only I am not able to track "new stocks" because they are not stored in my cash.

**Comment by ValueRaider** [comment]
We think we've fixed in branch `hotfix/decryption`, please test and feedback.

**Comment by alBronko** [comment]
I have a delay between pulls, so mine is now fine. Thank you, guys!

**Comment by Rogach** [comment]
@ValueRaider Tested hotfix, works for me.

**Comment by Tcarter20052005** [comment]
@ValueRaider Also Tested hot fix and it works for me.

**Comment by igullage** [comment]
@ValueRaider hotfix worked for me. My scripts are running properly again. Thanks.

**Comment by ValueRaider** [comment]
@idan6767 #1080

**Comment by idan6767** [comment]
> @alBronko Are you still having trouble? Are you definitely running the branch up-to-date? I suspect out-of-date because your line number doesn't match.

Can u please explain exactly how to use the "hotfix/decryption" fix? im pretty new here. what is this "BRANCH"? how can i use it to fix?

**Comment by idan6767** [comment]
> hotfix/decryption

thanks, but i get this error:

 'git+https:' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ValueRaider** [comment]
@idan6767 Wrong place for that discussion, post in #1080

**Comment by allan-silverstein** [comment]
It is working for me now.  I had a typo in import statement so it was referencing original pip install.
Thank you for fixing.

**Comment by hepizoj22** [comment]
hotfix/decryption works. thank you for your hard work

**Comment by ValueRaider** [comment]
@waichan-bt Create a new Issue.

**Comment by ValueRaider** [comment]
PIP release out.

**Comment by waichan-bt** [comment]
which one to install using pip?  Do I still create a new issue for my sqlalchemy.exc.InterfaceError issue?

**Comment by havedill** [comment]
`pip install --upgrade yfinance` - Working ty

**Comment by waichan-bt** [comment]
works great now.  Thanks for all your support!

**Comment by krisannaert** [comment]
I have upgraded to 0.2.5 and updated the code to use the basic_info in stead of info for price values but for Ticker EUR=X I am getting the following:
EUR=X: Yahoo did not return share count in date range 2021-07-26 00:00:00+01:00 -> 2023-01-26 00:00:00+00:00.

  File "yahoo.py", line 22, in <module>
    for key in sorted(tk.basic_info.keys()):
  File "\AppData\Roaming\Python\Python310\site-packages\yfinance\base.py", line 85, in keys
    attrs = utils.attributes(self)
  File "\AppData\Roaming\Python\Python310\site-packages\yfinance\utils.py", line 59, in attributes
    return {
  File "\AppData\Roaming\Python\Python310\site-packages\yfinance\utils.py", line 61, in <dictcomp>
    if name[0] != '_' and name not in disallowed_names and hasattr(obj, name)}
  File "\AppData\Roaming\Python\Python310\site-packages\yfinance\base.py", line 358, in market_cap
    self._mcap = self.shares * self.last_price
  File "\AppData\Roaming\Python\Python310\site-packages\yfinance\base.py", line 201, in shares
    raise Exception(f"{self._tkr.ticker}: Cannot retrieve share count for calculating market cap")
Exception: EUR=X: Cannot retrieve share count for calculating market cap

**Comment by ValueRaider** [comment]
@krisannaert Create a new Issue

**Comment by spot92** [comment]
How long is the lag from PIP release to conda relase?

**Comment by DolevAlgam** [comment]
Thanks! This module is helping so much 🫶🏼

**Comment by CalvinGreen94** [comment]
Receiving error for yfinance import .. 



Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

EX:

stock.balance_sheet
stock.shares

**Comment by ValueRaider** [comment]
It is in and was working, for a whole 7 hours it seems before Yahoo changed yet again.

Apparently there's a better way to handle Yahoo's counters, just needs implementation - #1338

**Comment by CalvinGreen94** [comment]
I have been through opened issues, did the necessary pip installs. Any news on the fix ?

**Comment by chzhong25346** [comment]
msft.basic_info still working

**Comment by grzesir** [comment]
Still getting an issue with ticker.info

Code:
`import yfinance as yf

ticker = yf.Ticker("SPY")
ticker.info`

Traceback:
`Exception                                 Traceback (most recent call last)
/Users/robertgrzesik/Development/lumivest_bot_server/scratchpad.ipynb Cell 63 in <cell line: 4>()
      [1](vscode-notebook-cell:/Users/robertgrzesik/Development/lumivest_bot_server/scratchpad.ipynb#Y115sZmlsZQ%3D%3D?line=0) import yfinance as yf
      [3](vscode-notebook-cell:/Users/robertgrzesik/Development/lumivest_bot_server/scratchpad.ipynb#Y115sZmlsZQ%3D%3D?line=2) ticker = yf.Ticker("SPY")
----> [4](vscode-notebook-cell:/Users/robertgrzesik/Development/lumivest_bot_server/scratchpad.ipynb#Y115sZmlsZQ%3D%3D?line=3) ticker.info

File ~/opt/anaconda3/lib/python3.8/site-packages/yfinance/ticker.py:142, in Ticker.info(self)
    140 @property
    141 def info(self) -> dict:
--> 142     return self.get_info()

File ~/opt/anaconda3/lib/python3.8/site-packages/yfinance/base.py:1220, in TickerBase.get_info(self, proxy)
   1218 def get_info(self, proxy=None) -> dict:
   1219     self._quote.proxy = proxy
-> 1220     data = self._quote.info
   1221     return data

File ~/opt/anaconda3/lib/python3.8/site-packages/yfinance/scrapers/quote.py:96, in Quote.info(self)
     93 @property
     94 def info(self) -> dict:
     95     if self._info is None:
---> 96         self._scrape(self.proxy)
     97         self._scrape_complementary(self.proxy)
     99     return self._info
...
--> 190         raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
    192 decoded_stores = json.loads(plaintext)
    193 return decoded_stores

Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

**Comment by grzesir** [comment]
Sorry, I don't understand why my comment was deleted. Does that mean that you're aware of the issue and working on it or that you don't plan to fix?

**Comment by ValueRaider** [comment]
We're aware and want it fixed. But "plan to" is a strong word, all work here is voluntary.

**Comment by grzesir** [comment]
Ok, thank you. It's definitely annoying how Yahoo keeps changing its API, it keeps affecting our project https://github.com/Lumiwealth/lumibot

For now, I'm going to make lumibot less dependent on ticker.info(). Thank you for all your hard work!

**Comment by CaledoniaProject** [comment]
Still failing with balance sheet: `Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

```
import yfinance as yf

msft = yf.Ticker("MSFT")
print(msft.balance_sheet)
```

**Comment by CaledoniaProject** [comment]
OK, fixed by updating the keys.

**Comment by dkim777** [comment]
Still not working for me.
------------------------------
\yfinance\data.py", line 190, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
**Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers**

**Comment by luojian8313** [comment]
basic_info is not working for some stocks, e.g. AMC

ticker = yf.Ticker("AMC")
ticker.basic_info['shares']

it returns:
AMC: Yahoo did not return share count in date range 2021-07-27 00:00:00-04:00 -> 2023-01-26 00:00:00-05:00
Traceback (most recent call last):
  File "/Users/jianluo/Desktop/Python_Projects/MyProject/stock/yf_test.py", line 5, in <module>
    ticker.basic_info['shares']
....
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

**Comment by CaledoniaProject** [comment]
Just edit `yfinance/data.py` with the correct AES password would work:

```
def decrypt_cryptojs_aes_stores(data):
    encrypted_stores = data['context']['dispatcher']['stores']

    password = None
```

The password can be easily retrieved with a script.

**Comment by alimjahagirdar** [comment]
facing this error, when this will be fixed ?

(yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers)

msft.info

**Comment by cajuncoder** [comment]
As of today, I'm getting this error with any and all tickers and requests. Even just single requests for any given ticker.
My code worked just fine last week. Hadn't ran it this week so I didn't notice until today.

**Comment by allan-silverstein** [comment]
I had this working with the hotfix but now I tried a pip install yfinance --upgrade and it is not working again.  The error I"m getting is:
yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

**Comment by suntech123** [comment]
Still throwing error when i updated package to 0.2.6

Exception                                 Traceback (most recent call last)
[<ipython-input-3-c765047571e4>](https://localhost:8080/#) in <module>
----> 1 yf.Ticker("BATAINDIA.NS").info

6 frames
[/usr/local/lib/python3.8/dist-packages/yfinance/data.py](https://localhost:8080/#) in decrypt_cryptojs_aes_stores(data)
    188                 pass
    189         if not success:
--> 190             raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
    191 
    192     decoded_stores = json.loads(plaintext)

Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

**Comment by STEVEN-STARK** [comment]
Using Python 3.9.1 running on Windows 10 and yfinance version 0.2.6.

Still seeing error:

Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

when attempting to retrieve price for single ticker symbol.

**Comment by JECSand** [comment]
@ValueRaider I maintain YahooFinancials. I fixed this earlier, had to dynamically regex the keys from the pages main.js file.

The function that gets the keys "_get_decryption_keys()" starts on l**ine 147**.
https://github.com/JECSand/yahoofinancials/pull/125/files

Don't hesitate to use it:
```Python
def _get_decryption_keys(soup):
     key_count = 4
     re_script = soup.find("script", string=re.compile("root.App.main")).text
     re_data = loads(re.search("root.App.main\s+=\s+(\{.*\})", re_script).group(1))
     re_data.pop("context", None)
     key_list = list(re_data.keys())
     if re_data.get("plugins"):  # 1) attempt to get last 4 keys after plugins
         ind = key_list.index("plugins")
         if len(key_list) > ind+1:
             sub_keys = key_list[ind+1:]
             if len(sub_keys) == key_count:
                 re_obj = {}
                 missing_val = False
                 for k in sub_keys:
                     if not re_data.get(k):
                         missing_val = True
                         break
                     re_obj.update({k: re_data.get(k)})
                 if not missing_val:
                     return re_obj
     re_keys = []    # 2) attempt scan main.js file approach to get keys
     prefix = "https://s.yimg.com/uc/finance/dd-site/js/main."
     tags = [tag['src'] for tag in soup.find_all('script') if prefix in tag.get('src', '')]
     for t in tags:
         urlopener_js = UrlOpener()
         response_js = urlopener_js.open(t)
         if response_js.status_code != 200:
             time.sleep(random.randrange(10, 20))
             response_js.close()
         else:
             r_data = response_js.content.decode("utf8")
             re_list = [
                 x.group() for x in re.finditer(r"context.dispatcher.stores=JSON.parse((?:.*?\r?\n?)*)toString", r_data)
             ]
             for rl in re_list:
                 re_sublist = [x.group() for x in re.finditer(r"t\[\"((?:.*?\r?\n?)*)\"\]", rl)]
                 if len(re_sublist) == key_count:
                     re_keys = [sl.replace('t["', '').replace('"]', '') for sl in re_sublist]
                     break
             response_js.close()
         if len(re_keys) == key_count:
             break
     re_obj = {}
     missing_val = False
     for k in re_keys:
         if not re_data.get(k):
             missing_val = True
             break
         re_obj.update({k: re_data.get(k)})
     if not missing_val:
         return re_obj
     return None
```

**Comment by chnusti** [comment]
> Using Python 3.8.1  and yfinance version 0.2.6.
> 
> Still seeing error:
> 
> Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers
> 
> when attempting to retrieve price for single ticker symbol.

unfortunately same on my end

**Comment by havedill** [comment]
Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers

I'm getting this error today on yfinance-0.2.6

**Comment by ValueRaider** [comment]
Thanks @JECSand, I'll code this up. Btw if you think there's scope for merging the two projects, drop me an email. Seems inefficient to have multiple scrapers basically doing same thing.

**Comment by ashishkhairnar** [comment]
> Just edit `yfinance/data.py` with the correct AES password would work:
> 
> 
> 
> ```
> 
> def decrypt_cryptojs_aes_stores(data):
> 
>     encrypted_stores = data['context']['dispatcher']['stores']
> 
> 
> 
>     password = None
> 
> ```
> 
> 
> 
> The password can be easily retrieved with a script.
> 
> 

Having same issues lately. 

I will try this until library gets fixed.

**Comment by ValueRaider** [comment]
Pull request @ #1353 , test it please

**Comment by ValueRaider** [comment]
@SymbReprUnlim Doesn't help, read this thread.

**Comment by tomekkurzydlak** [comment]
> Pull request @ #1353 , test it please

works for me, thank you!

**Comment by ValueRaider** [comment]
PIP release out

**Comment by jiangoz** [comment]
Using version 0.2.7, `'regularMarketPrice'` seems to be missing from the Ticker info object

**Comment by lucas03** [comment]
there should be error message, use `ticker.basic_info["last_price"]` instead

**Comment by ValueRaider** [comment]
@jiangoz It should print a message explaining where it's moved to.

**Comment by jiangoz** [comment]
> @jiangoz It should print a message explaining where it's moved to.

I meant it's also not in `Ticker.fast_info`

Is `last_price` equivalent to `regularMarketPrice` ?

**Comment by galashour** [comment]
The attribute 'beta' used to be in Ticker.Info, but now couldn't find it also in the metadata or fast_info. Any idea where it was relocated to?

**Comment by ValueRaider** [comment]
> Is `last_price` equivalent to `regularMarketPrice` ?

Yes, and to `info["ccurrentPrice"]`, I never saw a difference.

I haven't moved `beta`. The relocated keys are defined at top of `quote.py`.

**Comment by galashour** [comment]
@ValueRaider you are right, it seems I checked with MSFT and for some reason for that ticker while the attribute exists it returns 'None'. I check with another ticker (e.g., AAPL) and the value was returned. 
Thanks.

**Comment by ValueRaider** [comment]
The data was always there, encrypted. They just changed encryption parameters.

Throttling has always existed but it depends on the data you request. `info` is worst for throttling (10-100/hour), financials maybe better, price data much better (~1000/hour). It may have gotten worse 1-2 years ago, but that's before my time. Maybe some old-timers can correct me.

**Comment by eleinv** [comment]
The data was there years ago in raw format. Before crumb there was no throttling, now is there an algorithm you must follow to get the data without errors, because of throttling

**Comment by machine700** [comment]
version 0.2.7

data = yf.Ticker("AMD").info

#**These are not working, and there might be others**
print(data['marketCap'])
print(data['regularMarketPrice'])
print(data['trailingAnnualDividendRate'])

**And I haven't tried others yet.**

**Comment by dowens375** [comment]
I would like to thank you for your excellent work!

**Comment by ValueRaider** [comment]
I'm not seeing any more reports of the decryption failing, but instead new issues, so will lock this thread. If decryption fails again I'll unlock.

**Comment by ValueRaider** [comment]
Only post here if you are experiencing decryption problems. If you issue is different - some might say new - make a New Issue.

**Comment by waichan-bt** [comment]
Cannot install latest version using "pip3 install yfinance", still showing 0.2.4; when trying to force it by "pip3 install version==0.2.7 yfinance", the version cannot be found.

**Comment by bma-diy** [comment]
workaround:

info = yf.Ticker(symbol).info

type(info)
yfinance.scrapers.quote.InfoDictWrapper

convert it to dictionary and your code should work:

info = dict(info)

**Comment by vishwesh5544** [comment]
Upgraded to yfinance 0.2.9, trying to fetch Ticker.info['currentPrice'] but still getting the decryption error as follows:

Exception: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption:

**Comment by ValueRaider** [comment]
I noticed this appearing more often today, affecting financials too. Maybe Yahoo lowered the threshold for spam, where they return bad data that can't be decrypted.

I think solution is to use `request_cache` to minimise spam (see README) + Git branch `feature/session-prune-v2` to remove bad data from cache. Can you try?

**Comment by vishwesh5544** [comment]
> @vishwesh5544
> 
> > Upgraded to yfinance 0.2.9
> 
> No you didn't

i ran pip install --upgrade yfinance

**Comment by ValueRaider** [comment]
That's not how you confirm the version, go read the "New Issue" message.

**Comment by vishwesh5544** [comment]
> That's not how you confirm the version, go read the "New Issue" message. 0.2.9 doesn't contain that message.

Issue solved for me after restarting.

**Comment by Dr-DFTD3** [comment]
I am using yfinance 0.2.10
Python 3.10

I have been working on an app for a few days and everything was fine. As of now, I am still able to retrieve historical price data, but anything related to .info is not working

import yfinance as yf
catData = yf.Ticker('CAT')
info = catData.info['forwardPE']
print(info)

Produces the following warning and error. A few hours ago everything was fine.
WARNING: No decryption keys could be extracted from JS file. Falling back to backup decrypt methods.
Traceback (most recent call last):
  File "/Users/joegonzalez/Dropbox/day_trading/stockViewApp/v1/sviewer.py", line 52, in <module>
    info = catData.info['forwardPE']
File "/Users/joegonzalez/miniconda3/envs/stock/lib/python3.10/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/Users/joegonzalez/miniconda3/envs/stock/lib/python3.10/site-packages/yfinance/base.py", line 1462, in get_info
    data = self._quote.info
  File "/Users/joegonzalez/miniconda3/envs/stock/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 95, in info
    self._scrape(self.proxy)
  File "/Users/joegonzalez/miniconda3/envs/stock/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 124, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "/Users/joegonzalez/miniconda3/envs/stock/lib/python3.10/site-packages/yfinance/data.py", line 41, in wrapped
    return func(*args, **kwargs)
  File "/Users/joegonzalez/miniconda3/envs/stock/lib/python3.10/site-packages/yfinance/data.py", line 311, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data, keys)
  File "/Users/joegonzalez/miniconda3/envs/stock/lib/python3.10/site-packages/yfinance/data.py", line 162, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response")
Exception: yfinance failed to decrypt Yahoo data response

**Comment by dkim777** [comment]
Installed 0.2.10
still getting error.
-----------------------
\Python39\site-packages\yfinance\data.py", line 311, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data, keys)
  File "C:\Users\dkim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yfinance\data.py", line 162, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response")
Exception: yfinance failed to decrypt Yahoo data response

**Comment by EmirEgilli** [comment]
Installed the 0.2.10 version and i still have this issue on my algo that i use to obtain a treemap for various stocks' performance. Issue seems to be isolated to the "yf.Ticker(symbol).info" where i replicate it at; ".info['sector']" and ".info['industry']"

Everything seems to work fine with ".fast_info['last_price']". Any workaround for sector and industry info is much appreciated.

**Comment by ValueRaider** [comment]
@Dr-DFTD3 @dkim777 @EmirEgilli I've started a new Issue thread for this. #1407

**Comment by keyixx** [comment]
> I've quickly tested and working for me.
> 
> Error message tells us there are 8 fields when `yfinance` expected 1. But there is a bug in generating that error message, that's why all print same - can you try again with Git branch `hotfix/decryption`.

Guys, yahooquery is work 

------------------------------
pip install yahooquery
from yahooquery import Ticker

**Comment by Travis-Barton** [comment]
Same issue on 0.2.11
