### ISSUE TITLE
0.2.19b3: download(): KeyError when storing Tracebacks

### ISSUE THREAD

**Issue by PeterSchober005** [ranaroussi/yfinance#1539]
- Simple code that reproduces your problem, that we can copy-paste-run:

```
ticker_list_r3000=pd.read_csv("RUSSELL3000.csv", sep='\t', dtype=str ,header=None)
ticker_list_r3000=ticker_list_r3000.iloc[:,0].tolist()
ticker_list_r3000.remove("MSGE")
ticker_list_r3000.remove("-")
stockdata = yf.download(ticker_list_r3000,'2021-1-1', group_by="ticker",auto_adjust=True, threads=True)
```

Please use the file attached to this message.

- Exception message with full traceback, or proof `yfinance` returning bad data:
  The pre-release version 0.2.19b3 generates an error bug (UNDESIRED BEHAVIOR!!!!):
         https://github.com/ranaroussi/yfinance/issues/1526#issuecomment-1559588523
  The release version  0.2.18 does not generate an error bug (DESIRED BEHAVIOR!!!!):
         https://github.com/ranaroussi/yfinance/issues/1526#issuecomment-1559707072

It is not desired that an error bug is generated if some tickers can not be downloaded when a large list of tickers is passed on to yf.download. When the user gives a long list of tickers to yf.download, chances are that some tickers can not be downloaded. If this is the case, yf-download should simply continue with the next symbol without generating a bug. It should simply continue to behave like up in version 0.2.18. It should not generate a bug like in 0.2.19b3.

- `yfinance` version and Python version:
   Python version: 3.11.2
   Yfinance: 0.2.19b3 (=pre-release version) and 0.2.18 (=release version)

- Operating system type: Windows 10

[Russell3000.csv](https://github.com/ranaroussi/yfinance/files/11546474/Russell3000.csv)

**Comment by ValueRaider** [comment]
Try branch `fix/download-logging`. I'm confident it will fix bug, but want to know if `download` has other problems.

**Comment by PeterSchober005** [comment]
@ValueRaider Thanks for fix!
Unfortunately, the error bug is still there:

Input:
start = time.time()
stockdata = yf.download(ticker_list_r3000,'2021-1-1', group_by="ticker",auto_adjust=True, threads=True)
stockdata.index=pd.DatetimeIndex(stockdata.index)
print(time.time()-start)

Output:
[*                      3%                       ]  71 of 2635 completed
ERROR CWENA: No timezone found, symbol may be delisted
[***                    6%                       ]  168 of 2635 completed
ERROR PFHC: No timezone found, symbol may be delisted
[***                    7%                       ]  194 of 2635 completed
ERROR LGFB: No timezone found, symbol may be delisted
[*****                 10%                       ]  252 of 2635 completed
ERROR BRKB: No timezone found, symbol may be delisted
[*********             19%                       ]  513 of 2635 completed
ERROR GTXI: No timezone found, symbol may be delisted
[*************         28%                       ]  746 of 2635 completed
ERROR BHM WI: No timezone found, symbol may be delisted
[**************        29%                       ]  768 of 2635 completed
ERROR CR WI: No timezone found, symbol may be delisted
[*****************     36%                       ]  948 of 2635 completed
ERROR P5N994: No timezone found, symbol may be delisted
[******************    38%                       ]  1011 of 2635 completed
ERROR RTYM3: No timezone found, symbol may be delisted
[********************  41%                       ]  1071 of 2635 completed
ERROR TFM: No price data found, symbol may be delisted (1d 2021-1-1 -> 2023-05-25)
[********************  41%                       ]  1072 of 2635 completed
ERROR HEIA: No timezone found, symbol may be delisted
[**********************46%                       ]  1204 of 2635 completed
ERROR GEFB: No timezone found, symbol may be delisted
[**********************47%                       ]  1245 of 2635 completed
ERROR XTSLA: No timezone found, symbol may be delisted
[**********************50%                       ]  1312 of 2635 completed
ERROR LENB: No timezone found, symbol may be delisted
[**********************50%                       ]  1322 of 2635 completed
ERROR BFA: No timezone found, symbol may be delisted
[**********************56%**                     ]  1475 of 2635 completed
ERROR BFB: No timezone found, symbol may be delisted
[**********************56%**                     ]  1486 of 2635 completed
ERROR ESM3: No timezone found, symbol may be delisted
[**********************64%******                 ]  1688 of 2635 completed
ERROR SAFE WI: No timezone found, symbol may be delisted
[**********************72%**********             ]  1900 of 2635 completed
ERROR UHALB: No timezone found, symbol may be delisted
[**********************79%*************          ]  2075 of 2635 completed
ERROR RXO WI: No timezone found, symbol may be delisted
[**********************81%**************         ]  2130 of 2635 completed
ERROR MSFUT: No timezone found, symbol may be delisted
[**********************83%***************        ]  2174 of 2635 completed
ERROR ARD: No timezone found, symbol may be delisted
[**********************85%****************       ]  2227 of 2635 completed
ERROR MOGA: No timezone found, symbol may be delisted
[**********************91%*******************    ]  2403 of 2635 completed
ERROR LGFA: No timezone found, symbol may be delisted
[**********************98%********************** ]  2587 of 2635 completed
ERROR ADRO: No timezone found, symbol may be delisted
[*********************100%***********************]  2635 of 2635 completed
ERROR 
25 Failed downloads:
ERROR ['CWENA', 'PFHC', 'LGFB', 'BRKB', 'GTXI', 'BHM WI', 'CR WI', 'P5N994', 'RTYM3', 'HEIA', 'GEFB', 'XTSLA', 'LENB', 'BFA', 'BFB', 'ESM3', 'SAFE WI', 'UHALB', 'RXO WI', 'MSFUT', 'ARD', 'MOGA', 'LGFA', 'ADRO']: No timezone found, symbol may be delisted
ERROR ['TFM']: No price data found, symbol may be delisted (1d 2021-1-1 -> 2023-05-25)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[3], line 2
      1 start = time.time()
----> 2 stockdata = yf.download(ticker_list_r3000,'2021-1-1', group_by="ticker",auto_adjust=True, threads=True)
      3 stockdata.index=pd.DatetimeIndex(stockdata.index)
      4 print(time.time()-start)

File [c:\Users\peter\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\multi.py:178](file:///C:/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py:178), in download(tickers, start, end, actions, threads, ignore_tz, group_by, auto_adjust, back_adjust, repair, keepna, progress, period, show_errors, interval, prepost, proxy, rounding, timeout)
    [176](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=175) tbs = {}
    [177](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=176) for ticker in shared._ERRORS:
--> [178](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=177)     tb = shared._TRACEBACKS[ticker]
    [179](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=178)     if not tb in tbs:
    [180](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=179)         tbs[tb] = [ticker]

KeyError: 'CWENA'

**Comment by ValueRaider** [comment]
> for ticker in shared._ERRORS:

This tells me you have not loaded the Git branch.

**Comment by PeterSchober005** [comment]
I am running the following command for a second time... (interestingly this time, I am getting a warning):

pip install git+https://github.com/ranaroussi/yfinance.git@fix/download-logging




Collecting git+https://github.com/ranaroussi/yfinance.git@fix/download-logging
  Cloning https://github.com/ranaroussi/yfinance.git (to revision fix/download-logging) to c:\users\peter\appdata\local\temp\pip-req-build-_98tksxf
  Running command git clone --filter=blob:none --quiet https://github.com/ranaroussi/yfinance.git 'C:\Users\peter\AppData\Local\Temp\pip-req-build-_98tksxf'
  WARNING: Did not find branch or tag 'fix/download-logging', assuming revision or ref.
  Running command git checkout -q fix/download-logging
  error: pathspec 'fix/download-logging' did not match any file(s) known to git
  error: subprocess-exited-with-error

  × git checkout -q fix/download-logging did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q fix/download-logging did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ValueRaider** [comment]
> I'll merge

Because I merged it. Doesn't exist anymore.

**Comment by PeterSchober005** [comment]
Ok, but I am still getting the error and I have executed the line with the git branch and received no error when executing it. So I guess it was implemented on my side... but I am might be wrong... 

KeyError                                  Traceback (most recent call last)
Cell In[3], line 2
      1 start = time.time()
----> 2 stockdata = yf.download(ticker_list_r3000,'2021-1-1', group_by="ticker",auto_adjust=True, threads=True)
      3 stockdata.index=pd.DatetimeIndex(stockdata.index)
      4 print(time.time()-start)

File [c:\Users\peter\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\multi.py:178](file:///C:/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py:178), in download(tickers, start, end, actions, threads, ignore_tz, group_by, auto_adjust, back_adjust, repair, keepna, progress, period, show_errors, interval, prepost, proxy, rounding, timeout)
    [176](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=175) tbs = {}
    [177](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=176) for ticker in shared._ERRORS:
--> [178](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=177)     tb = shared._TRACEBACKS[ticker]
    [179](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=178)     if not tb in tbs:
    [180](file:///c%3A/Users/peter/AppData/Local/Programs/Python/Python311/Lib/site-packages/yfinance/multi.py?line=179)         tbs[tb] = [ticker]

KeyError: 'UHALB'

**Comment by ValueRaider** [comment]
> for ticker in shared._ERRORS:

You :clap: are :clap: not :clap: running :clap: the :clap: branch

**Comment by PeterSchober005** [comment]
What do you mean with PIP pre-release out? 
Should I re-install the pre-release since the fix was merged into it?

**Comment by PeterSchober005** [comment]
I am removing the pre release and re-installing it again. I will run the download function again with the latest pre-release

**Comment by ValueRaider** [comment]
https://softhints.com/install-pre-release-package-pip-python

**Comment by ValueRaider** [comment]
I repeat:

> 177 for ticker in shared._ERRORS:
> --> 178 tb = shared._TRACEBACKS[ticker]

This tells me you have the wrong version. I have successfully installed latest beta via PIP so problem is your end.

**Comment by PeterSchober005** [comment]
Wrong version of yfinance pre-release?
this is what I execute: pip install yfinance --pre

**Comment by PeterSchober005** [comment]
I just re-installed yfinance and now it is installing version yfinance-0.2.19b4... I will re-run the code and then confirm that you are right as always :-)

**Comment by PeterSchober005** [comment]
Yes, @ValueRaider, I confirm. Error bug is solved. Running well and fluently. Many thanks for the fix and the new pre-release!!! :)
