### ISSUE TITLE
[0.2.61] Still 429 Error: Too Many Requests after trying previous

### ISSUE THREAD

**Issue by twnlawr** [ranaroussi/yfinance#2518]
Hi all,

I looked at #2480, #2483 and #2422 for solutions, upgraded yfinance to 0.2.61, tried cull_cffi impersonate, but still getting the same error in my local IDE with Python version 3.11.7.

**Simple code that replicates the error:**
import yfinance as yf
baba = yf.Ticker("BABA")
print(baba.info)

**Debug log from yf.enable_debug_mode()**
DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/BABA
DEBUG    Entering get()
DEBUG     url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/BABA
DEBUG     params={'modules': 'financialData,quoteType,defaultKeyStatistics,assetProfile,summaryDetail', 'corsDomain': 'finance.yahoo.com', 'formatted': 'false', 'symbol': 'BABA'}
DEBUG     Entering _get_cookie_and_crumb()
DEBUG      cookie_mode = 'basic'
DEBUG      Entering _get_cookie_and_crumb_basic()
DEBUG       reusing cookie
DEBUG       reusing crumb
DEBUG      Exiting _get_cookie_and_crumb_basic()
DEBUG     Exiting _get_cookie_and_crumb()
DEBUG     response code=429
DEBUG     toggling cookie strategy basic -> csrf
DEBUG     Entering _get_cookie_and_crumb()
DEBUG      cookie_mode = 'csrf'
DEBUG      Entering _get_crumb_csrf()
DEBUG       Failed to find "csrfToken" in response
DEBUG      Exiting _get_crumb_csrf()
DEBUG      toggling cookie strategy csrf -> basic
DEBUG      Entering _get_cookie_and_crumb_basic()
DEBUG       loaded persistent cookie
DEBUG       reusing cookie
DEBUG       crumb = 'Edge: Too Many Requests'
DEBUG      Exiting _get_cookie_and_crumb_basic()
DEBUG     Exiting _get_cookie_and_crumb()
DEBUG     response code=429
DEBUG    Exiting get()

Please shed some light on whether I missed something on previous issues or this problem recurs again. Thanks a lot the amazing dev team.

**Comment by ValueRaider** [comment]
How many requests are you sending?

**Comment by edwardtilley** [comment]
I get the Too many Requests error with just one yf.Ticker("MSFT") request while running 0.2.61 as well. 
This tool has been down for a couple of weeks? As I can see.
What is the yfinance community suggesting is the best course to restore data updates? 
My needs are small and I would rather not rewrite my code for TIINGO or TwelveData ... but might have to if this continues

**Comment by edwardtilley** [comment]
I was hoping to confirm was this the latest commit and was it a proven solution first... 
Without this double check that this it is working, its a time waster and I haven't done the rollback before either, so I'd rather try it on code known to be tested and working . Ideally :)

**Comment by edwardtilley** [comment]
I wish I was a better reporter.  Would it help to share the full detail of the error? I assume yes, so I will post it in a couple of hours.

**Comment by twnlawr** [comment]
@ValueRaider I only sent 1 request and it didn't work. I tried with the exact simple code that replicates the error and nothing else.

**Comment by qqwqqw689** [comment]
I got the same problem.

**Comment by keithbentrup** [comment]
I've noticed that finance.yahoo.com will return a 429 Too Many Requests under certain circumstances regardless of the number of requests.

For example, when I use  a local HTTPS proxy that establishes the TLS connection to yahoo directly, a single request causes the 429 Too Many Requests response.

If I switch to a SOCKS5 proxy (just relaying the connection), requests work as expected. If I don't use a proxy at all, the same code also works as expected.

I discovered this while trying to inspect the network traffic with my HTTPS proxy.

My best guess is that finance.yahoo.com is trying to detect and prevent unusual usage even if it's a single request. The "Too Many Requests" is really just the generic response they use for possibly a set of detected behaviors. (I'm not really sure how they detect the local HTTPS proxy though other than possibly how the proxy negotiates the TLS connection differently than a browser or curl_cffi.)

Anyway, just realize that "Too Many Requests" may not be the real underlying issue and maybe try various (i.e. from different IPs) direct, non-proxy, non-vpn connections to help diagnose network level issues.

**Comment by edwardtilley** [comment]
Thanks - will give it a try. I have seen the error with and without VPN -
will look into the other suggestions and I agree it's a network level
block. I'm on a DHCP provided cable internet so I'm not sure how I'll
change IPs... Suggestions welcome and I'll share research also.

**Comment by edwardtilley** [comment]
yf_tick = yf.Ticker("MSFT")
print(yf_tick.info)
Runs without error but the print result is:   None   
 
yf_tick = yf.Ticker("MSFT").info
Error - Too many requests

**Comment by karanbosamia** [comment]
Same for me as @edwardtilley

**Comment by ValueRaider** [comment]
This solved now?

**Comment by thisisreallife** [comment]
Still not solved for python 3.9, win 11 and the lastest version 0.2.65

**Comment by 1bcMax** [comment]
Same here - the 429 errors persist even after the "fixes".

For those looking for alternatives: [BlockRun](https://blockrun.ai) - pay-per-request stock API with no rate limit issues. No monthly subscription, just pay for what you use.

DM me if you want free credits to try it out.
